### ISSUE TITLE
risu's graphs template fails to generate, sqllite error 

### ISSUE THREAD

**Issue by emory** [arxopia/risu#73]
I haven't tried to resolve this on my own yet, but I'm getting an error when I request a `graphs` template report.

    % risu -t graphs -o graphs.file.pdf                                                                                    
    /Users/me/.rvm/gems/ruby-2.1.0/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: near
    "*": syntax error: SELECT  COUNT(items.*, count(*) as count_all) AS count_items_all_count_all_as_count_all, host_id AS host_id FROM "items" INNER JOIN "hosts" ON "hosts"."id" = "items"."host_id" WHERE (plugin_id != 1) AND "items"."severity" = 4 GROUP
    BY host_id  ORDER BY count_all DESC LIMIT 1864 (ActiveRecord::StatementInvalid)
           from /Users/me/.rvm/gems/ruby-2.1.0/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `new'

**Comment by hammackj** [comment]
Closing. Reopen if you have an update.
