### ISSUE TITLE
New HostProperties attribute: UnsupportedProduct

### ISSUE THREAD

**Issue by mboman** [arxopia/risu#75]
New HostProperties attribute: UnsupportedProduct. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com

$ risu --version
risu: 1.7.1
Ruby Version: 1.9.3
Rubygems Version: 2.4.3

**Comment by hammackj** [comment]
Should be in 1.7.2. Let me know if they are not.
