### ISSUE TITLE
risu not installed in home directory

### ISSUE THREAD

**Issue by mrjim72** [arxopia/risu#78]
Here's one I've encountered now and again, but not in a long time.  I just slicked an old Dell laptop and installed Kali on it.  Risu was not installed in the home directory.

Instead, it's here:

/usr/local/rvm/gems/ruby-2.0.0-p598/gems/risu-1.7.3/

When I've installed risu on VMs lately, it makes the /root/risu directory.  I wonder what the difference is.

Here is what I'm running on this machine:

risu: 1.7.3
Ruby Version: 2.0.0
Rubygems Version: 2.4.5

**Comment by hammackj** [comment]
Strange it shouldn't make a .risu directory at all.

On Saturday, January 10, 2015, James K. Bishop <notifications@github.com>
wrote:

> Here's one I've encountered now and again, but not in a long time. I just
> slicked an old Dell laptop and installed Kali on it. Risu was not installed
> in the home directory.
>
> Instead, it's here:
>
> /usr/local/rvm/gems/ruby-2.0.0-p598/gems/risu-1.7.3/
>
> When I've installed risu on VMs lately, it makes the /root/risu directory.
> I wonder what the difference is.
>
> Here is what I'm running on this machine:
>
> risu: 1.7.3
> Ruby Version: 2.0.0
> Rubygems Version: 2.4.5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arxopia/risu/issues/78>.
>


-- 
Jacob Hammack
Jacob.Hammack@Hammackj.com
(210) 355-0036
http://www.hammackj.com

**Comment by mrjim72** [comment]
Hmm.  Doesn't appear to be an issue after all.  I was thinking that it wouldn't find my custom templates.  It did and they work.  :)
