### ISSUE TITLE
Risu won't stay installed on Kali

### ISSUE THREAD

**Issue by mrjim72** [arxopia/risu#79]
I mentioned this in a prior thread, but I thought it was a problem with a Kali VM.  I've just duplicated the problem on hard drive install.  Risu and RVM both become inoperable after reboot.  But all the files are still there.  Cranking back thorugh the install makes everything work again.  Any ideas?

Here's what I did:

root@kali:~# risu --version
bash: risu: command not found
root@kali:~# find / -name 'risu'
/usr/local/rvm/gems/ruby-2.0.0-p598/wrappers/risu
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/risu-1.7.3/lib/risu
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/risu-1.7.3/bin/risu
/usr/local/rvm/gems/ruby-2.0.0-p598/bin/risu
root@kali:~# rvm install 2.0.0
bash: rvm: command not found
root@kali:~# \curl -sSL https://get.rvm.io | bash -s stable
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.9.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc
gpg: Signature made Wed 07 Jan 2015 05:55:10 AM CST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-1.26.9.tgz'

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

\# Administrator,
\#
\#   Thank you for using RVM!
\#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
\#
\# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

root@kali:~# risu --version
bash: risu: command not found
root@kali:~# source /usr/local/rvm/scripts/rvm
root@kali:~# rvm use 2.0.0 --default
Using /usr/local/rvm/gems/ruby-2.0.0-p598
root@kali:~# gem install risu
Successfully installed risu-1.7.3
Parsing documentation for risu-1.7.3
unable to convert "\xFF" from ASCII-8BIT to UTF-8 for lib/risu/templates/data/nessuslogo.jpg, skipping
1 gem installed
root@kali:~# risu --version
risu: 1.7.3
Ruby Version: 2.0.0
Rubygems Version: 2.4.5
root@kali:~#

**Comment by hammackj** [comment]
Do you have the RVM specific stuff in your .bashrc/.bash_profile?

I think that has to run every time you launch a shell for it to load the GEM env, I use chruby personally these days instead of rvm.

This is the latest Kali image? I will download it and try.

**Comment by mrjim72** [comment]
It's 1.09a 32-bit.  There's no RVM stuff in the .bashrc file.  I tried to duplicate the lines in the BT VM that I use, but it didn't work with this install.

**Comment by hammackj** [comment]
Strange seems like a rvm issue with it not being loaded after reboot

On Saturday, January 10, 2015, James K. Bishop <notifications@github.com>
wrote:

> It's 1.09a 32-bit. There's no RVM stuff in the .bashrc file. I tried to
> duplicate the lines in the BT VM that I use, but it didn't work with this
> install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arxopia/risu/issues/79#issuecomment-69477950>.
>


-- 
Jacob Hammack
Jacob.Hammack@Hammackj.com
(210) 355-0036
http://www.hammackj.com

**Comment by hammackj** [comment]
You will need to do something like:

    echo "source $HOME/.rvm/scripts/rvm" >> ~/.bash_profile

To get to to load everytime you reboot

**Comment by mrjim72** [comment]
Hmm.  Did that and also found the RVM documentation for a root-only install which says do this before install:

<pre><code>echo 'export rvm_prefix="$HOME"' > /root/.rvmrc
echo 'export rvm_path="$HOME/.rvm"' >> /root/.rvmrc
</code></pre>

It also says "Please note that this is not a typical, or generally supported installation type" so I'm sure my mileage in doing it this way will vary.  I suppose I should set up a user account, but I'm used to doing everything on these pen testing boxes as root because that's all I use them for.

**Comment by hammackj** [comment]
Did changing that fix the issue?

I typically run as a user and use chruby instead of RVM for setting up my rubies

**Comment by mrjim72** [comment]
I haven't been able to install as a user.  I will try chruby.  More to come...

**Comment by mrjim72** [comment]
Here is my sticking point:

<pre><code>
jkb@kali:~$ \curl -sSL https://get.rvm.io | sudo bash -s stable
[sudo] password for jkb: 
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.9.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc
gpg: Signature made Wed 07 Jan 2015 05:55:10 AM CST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/root/.rvm/archives/rvm-1.26.9.tgz'

Upgrading the RVM installation in /root/.rvm/
Upgrade of RVM in /root/.rvm/ is complete.

# jkb,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

jkb@kali:~$ rvm install 2.0.0
Already installed ruby-2.0.0-p598.
To reinstall use:

    rvm reinstall ruby-2.0.0-p598

jkb@kali:~$ source /usr/local/rvm/scripts/rvm
jkb@kali:~$ rvm use 2.0.0 --default
Using /usr/local/rvm/gems/ruby-2.0.0-p598
jkb@kali:~$ sudo gem install risu
ERROR:  Error installing risu:
	risu requires RubyGems version >= 1.8.24. Try 'gem update --system' to update RubyGems itself.
jkb@kali:~$ gem update --system
Latest version currently installed. Aborting.
jkb@kali:~$ 
</code></pre>

What am I missing? :)

**Comment by hammackj** [comment]
Are you still having issues? Sorry I have been busy and forgot about this ticket.

**Comment by mrjim72** [comment]
Oh no worries.  I've been busy myself.  Yes, I'm still having the same issue.  I can install it under root, but it won't stay in the bash profile.  And then I get the same sticking point above as a user account.

**Comment by hammackj** [comment]
Just to be clear for my testing.

It will work as the root user and doesn't work as a normal user?

Latest version of Kali?

**Comment by mrjim72** [comment]
Yes.  It will install and run perfectly as root, but won't stay in the bash profile.  It will not install as a user, with the result being the error I posted earlier.  I'm thinking I must be missing a step in the user install.  I'm using the latest Kali version (1.0.9a) 32-bit version.

**Comment by hammackj** [comment]
Going to close this issue. I am using risu on Kali with no issues. Please let me know if you are still having issues.
