### ISSUE TITLE
New XML element: potential_vulnerability

### ISSUE THREAD

**Issue by emory** [arxopia/risu#81]
Output from nessus-6.3 contains a new element:

     New XML element detected: potential_vulnerability. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com

**Comment by hammackj** [comment]
Hi, do you have any context on the contents of the xml tag?

I will get this added to 1.7.5

**Comment by emory** [comment]
still on my list of things to do, it's gnarly digging through that xml i need to make some smaller files to make it easy

**Comment by hammackj** [comment]
Added in 1.7.5.
