### ISSUE TITLE
New XML element.

### ISSUE THREAD

**Issue by CyberTaoFlow** [arxopia/risu#87]
This is on 6.4

New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com
New XML element detected: agent. Please report this at http://github.com/arxopia/risu/issues/new or via email to risu@arxopia.com

**Comment by CyberTaoFlow** [comment]
Here is some context ( grep 'agent\>' -A5 -B5 myreport.nessus)

<solution>n/a</solution>
<synopsis>The list of open ports could be retrieved by netstat.</synopsis>
<plugin_output>Port 138/udp was found to be open</plugin_output>
</ReportItem>
<ReportItem port="137" svc_name="netbios-ns" protocol="udp" severity="0" pluginID="34220" pluginName="Netstat Portscanner (WMI)" pluginFamily="Port scanners">
<agent>windows</agent>
<description>Using the WMI interface, it is possible to get the open ports by running the netstat command remotely.</description>
<fname>wmi_netstat.nbin</fname>
<plugin_modification_date>2015/07/06</plugin_modification_date>
<plugin_name>Netstat Portscanner (WMI)</plugin_name>
<plugin_publication_date>2008/09/16</plugin_publication_date>

Here are the values present for the element in my report.

<agent>all</agent>
<agent>unix</agent>
<agent>windows</agent>

**Comment by CyberTaoFlow** [comment]
Err rather ...
`<solution>n/a</solution>`
`<synopsis>The list of open ports could be retrieved by netstat.</synopsis>`
`<plugin_output>Port 138/udp was found to be open</plugin_output>`
`</ReportItem>`
`<ReportItem port="137" svc_name="netbios-ns" protocol="udp" severity="0" pluginID="34220" pluginName="Netstat Portscanner (WMI)" pluginFamily="Port scanners">`
`<agent>windows</agent>`
`<description>Using the WMI interface, it is possible to get the open ports by running the netstat command remotely.</description>`
`<fname>wmi_netstat.nbin</fname>`
`<plugin_modification_date>2015/07/06</plugin_modification_date>`
`<plugin_name>Netstat Portscanner (WMI)</plugin_name>`
`<plugin_publication_date>2008/09/16</plugin_publication_date>`

**Comment by CyberTaoFlow** [comment]
I see this is in 1.7.5

**Comment by hammackj** [comment]
Thanks. I will get 1.7.5 released soon.

**Comment by hammackj** [comment]
This got added in 1.7.5.
