### ISSUE TITLE
Add support for attribute 'agent'

### ISSUE THREAD

**Issue by emory** [arxopia/risu#91]
``[!] unknown attribute 'agent' for Risu::Models::Plugin.``

Any chance this could be implemented in risu please?

**Comment by emory** [comment]
Example:

```
</HostProperties>
<ReportItem port="0" svc_name="general" protocol="tcp" severity="0" pluginID="19506" pluginName="Nessus Scan Information" pluginFamily="Settings">
<agent>all</agent>
<description>This plugin displays, for each tested host, information about the scan itself :
```

**Comment by hammackj** [comment]
Which version of risu are you using? I think 1.7.5 has support for the agent tag.

**Comment by emory** [comment]
```
❯ risu -v
risu: 1.7.6
Ruby Version: 2.2.5
Rubygems Version: 2.6.2
```

User error possible. I'm using nessus 6.5.6 and just exported this from a scan done with a previous release of nessus. (minor not major)

I'll enable debug…

**Comment by emory** [comment]
I removed the few references of ``<agent>all</agent>`` but there were only 25. Same result, so I think I'm misinterpreting the error. 

NOTE! I'm using a historical (i.e. older) database (sqlite) — is there perhaps a table change or something that accommodated this ``agent`` piece that my database lacks? I can create a new database and test that.

**Comment by emory** [comment]
(parenthetical; this seems to be working with a new database)

**Comment by emory** [comment]
Yup. It's working as expected with a new database. Sorry for clutter. Possible enhancement request to update/upgrade a database? Or is that not typical usage? I use risu to make large roll-ups of individual scans pretty often.

**Comment by hammackj** [comment]
I typically generate a database per engagement. I am looking to add diffing/trending inside of a single database (multiple scans) but I haven't done much work on that.
